services:
    query_bus:
        alias: simple_bus.query_bus

    simple_bus.query_bus:
        class: Ajgl\SimpleBus\Message\Bus\Middleware\CatchReturnMessageBusSupportingMiddleware
        public: false
        tags:
            - { name: message_bus, type: query, middleware_tag: query_bus_middleware }

    simple_bus.query_bus.delegates_to_message_handler_middleware:
        class: Ajgl\SimpleBus\Message\Handler\DelegatesToMessageHandlerAndCatchReturnMiddleware
        public: false
        arguments:
            - '@simple_bus.query_bus.query_handler_resolver'
        tags:
            - { name: query_bus_middleware, priority: -1000 }

    simple_bus.query_bus.class_based_query_bus_resolver:
        class: SimpleBus\Message\Name\ClassBasedNameResolver
        public: false

    simple_bus.query_bus.named_message_query_bus_resolver:
        class: SimpleBus\Message\Name\NamedMessageNameResolver
        public: false

    simple_bus.query_bus.callable_resolver:
        class: SimpleBus\Message\CallableResolver\ServiceLocatorAwareCallableResolver
        public: false
        arguments:
            - ['@service_container', 'get']

    simple_bus.query_bus.query_handler_map:
        class: SimpleBus\Message\CallableResolver\CallableMap
        public: false
        arguments:
            # collection of query handler service ids, will be provided by the RegisterHandlers compiler pass
            - []
            - '@simple_bus.query_bus.callable_resolver'

    simple_bus.query_bus.query_handler_resolver:
        class: SimpleBus\Message\Handler\Resolver\NameBasedMessageHandlerResolver
        public: false
        arguments:
            - '@simple_bus.query_bus.query_bus_resolver'
            - '@simple_bus.query_bus.query_handler_map'

    simple_bus.query_bus.finishes_query_before_handling_next_middleware:
        class: SimpleBus\Message\Bus\Middleware\FinishesHandlingMessageBeforeHandlingNext
        public: false
        tags:
            - { name: query_bus_middleware, priority: 1000 }